changed file structure, improved install script
renamed 'bin' to 'sgcheck-bin', because when having been installed the filename 'bin' would not be unique

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,18 +14,32 @@
 
 CMD_EXIT="exit"
 
+#SUB_FOLDER=sgcheck-bin
+
 # include global functions
-. ./bin/util/global
-. ./bin/util/settingsUtil
+. ./sgcheck-bin/util/global
+. ./sgcheck-bin/util/settingsUtil
+
+errLog="$HOME/sgcheck_err.log"
+> "$errLog"
+
+
+function execSafe ()
+{
+	$1 &>> "$errLog" ||
+		echo "error: $(cat $errLog)" && exit 1
+}
 
 # 1. copy to a specific location:
 echo -n "specify location where to install sgcheck? "
 read dest
+eval "dest=$(echo $dest)"
+echo "$dest"
 if [ ! -e "$dest" ]; then
 	echo -n "dest doesn't exist. create (y/n)? "
 	read input
 	if [ "$input" = "y" ]; then
-		mkdir "$dest"
+		execSafe "mkdir \"$dest\""
 	else if [ "$input" = "n" ]; then
 		echo "installation aborted"
 		exit 1
@@ -41,7 +55,8 @@ else
 	fi
 fi
 echo "copying files..."
-cp -r ./sgcheck ./bin "$dest"
+cp ./sgcheck "$dest"
+cp -r ./sgcheck-bin "$dest"
 ## 2. add the wd-file:
 #echo "WORKING_DIR=\"$dest\"" > $dest/workingdir
 # 2. create settings file:
diff --git a/sgcheck-bin/in b/sgcheck-bin/in
--- a/sgcheck-bin/in
+++ b/sgcheck-bin/in
@@ -1,4 +1,6 @@
 
+
+# variables:
 #SETTINGS_FOLDER
 #SETTINGS_FILE
 #SERVER
@@ -7,27 +9,21 @@
 #THIS_BASE
 
 #include global functions
-. ./bin/util/global
-. ./bin/util/filesUtil
+. ./sgcheck-bin/util/global
 
 #variables
 # to be set by user input:
-	RSYNC_OPTIONS=
 	SRC=
 	DEST=
-#others:
-	interactive=1 
-	SIMULATE=0
 
 #functions:
-
 
 RSYNC_OPTIONS="-verbose -printcmd"
 # read params:
 interactive="1"
 if [ $# -gt 0 ]; then
 	#read options:
-	while [ $# -gt 0 ]; do
+	while [ $# -gt 1 ]; do
 		case "$1" in
 			"--settings" )
 				shift
@@ -50,6 +46,22 @@ if [ $# -gt 0 ]; then
 		shift
 	done
 fi
+if [ $interactive == "0" ]; then
+	if [ $# != 1 ]; then
+		echo "wrong parameters"
+		exit 1
+	fi
+	#read params:
+	if [ "$1" != "" ]; then
+		SRC="$1"
+		if [ ! -e "$SRC" ]; then
+			echo "File '$SRC' not found!"
+			exit 1
+		fi
+	fi
+fi
+
+echo "$settingsDir"
 if [ "$settingsDir" != "" ]; then
 	setSettingsFolder "$settingsDir"
 	#if [ $? != 0 ]; then
@@ -65,19 +77,8 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
-
-if [ $interactive == "0" ]; then
-	if [ $# != 1 ]; then
-		echo "wrong parameters"
-		exit 1
-	fi
-	#read params:
-	if [ "$1" != "" ]; then
-		SRC="$1"
-	fi
-fi
 if [ $interactive != "0" ]; then
-	echo -en "enter a folder/file to check out:\n$SERVER_BASE"
+	echo -en "enter a folder/file to check in:\n$THIS_BASE"
 	read SRC
 	echo "enter additional options:"
 	echo "-destructive, -simulate(, or nothing)"
@@ -85,20 +86,17 @@ if [ $interactive != "0" ]; then
 	RSYNC_OPTIONS="$RSYNC_OPTIONS"" $RSYNC_OPTIONS_"
 fi
 
-# the actual source is SERVER_BASE || SRC
-SRC_FULL="$SERVER_BASE$SRC"
-# SERVERBASE || SRC is split into SRC_BASE and SRC_FILE
-#SRC_BASE=$(dirname "$SRC_FULL") 
-# SRC_FILE=$(basename "$SRC_FULL")
+#echo "Hi"
 
-if [ "$SERVER" != "" ] ; then
-	SRC_RSYNC=samuel@"$SERVER:$SRC_FULL"
-else
-	SRC_RSYNC="$SRC_FULL"
-fi
-#echo executing \'$CMD_COPY $RSYNC_OPTIONS "$SRC_RSYNC" "$THIS_BASE"\'
-$CMD_COPY --settings "$settingsDir" $RSYNC_OPTIONS "$SRC_RSYNC" "$THIS_BASE"
-if [ $SIMULATE == 0 ]; then
-	addToList "$SRC" #$SRC_FILE
-fi
-#scp -r "samuel@$SERVER:\"$SERVER_BASE$SRC\"" "$THIS_BASE"
+getOriginDir "$SRC"
+prependServer "$__result"
+DEST="$__result"
+echo "dest: $DEST"
+#if [ "$SERVER" != "" ] ; then
+	#DEST_RSYNC=samuel@"$SERVER:$DEST"
+#else
+	#DEST_RSYNC="$DEST"
+#fi
+
+#echo "excecuting" \'$CMD_COPY $RSYNC_OPTIONS "$THIS_BASE$SRC" "$DEST_RSYNC"\'
+$CMD_COPY --settings "$settingsDir" $RSYNC_OPTIONS "$THIS_BASE$SRC" "$DEST" 
