fixed a bug in the 'sgcheck rm' script
It didn't call init, so the THIS_BASE was not set and it tried to delete a wrong file

diff --git a/sgcheck-bin/rm b/sgcheck-bin/rm
--- a/sgcheck-bin/rm
+++ b/sgcheck-bin/rm
@@ -35,6 +35,13 @@ if [ "$settingsDir" != "" ]; then
 	setSettingsFolder "$settingsDir"
 fi
 
+# load settings:
+init
+if [ $? != 0 ]; then
+	echo "settings file not found!"
+	exit 1
+fi
+
 case $mode in
 	"file") removeI ;;
 	"list") removeFromListI ;;
