the sgcheck command works now. Uses a global environmental variable to find out the location of the scripts to call.
the install script writes necessary commands into $HOME/.bashrc:
	SG_SCRIPT_PATH= ...
	export SG_SCRIPT_PATH
the 'export ...' is necessary, so that the variable is defined inside scripts when they are being executed.

diff --git a/sgcheck-bin/util/global b/sgcheck-bin/util/global
--- a/sgcheck-bin/util/global
+++ b/sgcheck-bin/util/global
@@ -3,7 +3,7 @@
 #include functions to work with the settings file
 #. ./util/settingsUtil
 
-. ./sgcheck-bin/util/settingsUtil
+. $SG_SCRIPT_PATH/sgcheck-bin/util/settingsUtil
 
 
 
@@ -14,6 +14,7 @@ fi
 
 #constants:
 CMD_COPY="./bin/cp"
+errLog="$HOME/sgcheck_err.log"
 
 
 # Variables
@@ -108,6 +109,12 @@ function yesNoI ()
 		esac
 	done
 	return 0
+}
+
+function execSafe ()
+{
+	$1 &>> "$errLog" ||
+		echo "error: $(cat $errLog)" && exit 1
 }
 
 # $1: prog name
